name: Release Obsidian plugin

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Test scenario tags'
        required: true
        type: string
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build plugin
        run: |
          npm install
          npm run build
          npm run download

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          zip -r assets.zip themes.json themes/ highlights.json highlights/

          gh release create "$tag" \
            --title="$tag" \
            --draft assets.zip main.js manifest.json styles.css